# Generated by Django 4.1.1 on 2023-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('place', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='unname',
            new_name='uname',
        ),
    ]
