# Generated by Django 4.1.1 on 2023-11-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
