# Generated by Django 4.1.1 on 2023-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_emp_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publication_year', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
